### ISSUE TITLE
Please add different versions from GNU.org

### ISSUE THREAD

**Issue by armijnhemel** [pombredanne/gpl-history#1]
The versions found at https://www.gnu.org/licenses/old-licenses/gpl-2.0.html and https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt differ in the appendix.

HTML version:

one line to give the program's name and an idea of what it does.
Copyright (C) yyyy  name of author

Text version:

    <one line to give the program's name and a brief idea of what it does.>
    Copyright (C) <year>  <name of author>

The differences: angle brackets and "yyyy" instead of "year"

**Comment by pombredanne** [comment]
Do you know where it is positioned date-wise?

**Comment by armijnhemel** [comment]
Since it is the same as the latest version: my guess is the same as COPYING.6
