### ISSUE TITLE
known GPL2 versions (text)

### ISSUE THREAD

**Issue by armijnhemel** [pombredanne/gpl-history#16]
This is the complete list of text versions of the GPL license I have uncovered. In some cases it was hard to determine the correct date. The data that I am unsure of I have added in brackets.

| #      | date introduced/changed                | source                   |
|--------|----------------------------------------|--------------------------|
| [x] 1a | June 2, 1991                           | http://ftp.gnu.org/gnu/findutils/findutils-4.1.tar.gz (COPYING file dated June 2, 1991) |
|        |                                        | http://ftp.gnu.org/old-gnu/make/make-3.60-3.62.diff.gz (patch date recorded June 3, 1991) |
| [x] 1b | June 2, 1991                           | http://ftp.gnu.org/old-gnu/gcc/gcc-2.0.tar.bz2 |
| [x] 2  | November 26 or 29, 1995 or earlier     | http://ftp.gnu.org/old-gnu/gcc/gcc-2.7.2.tar.gz  (date on FTP server: November 29, 1995 but release announcements are dated November 26, 1995) |
|        | (October 26, 1995 or earlier)          | (COPYING file dated October 26, 1995) |
| [ ] 3  | February 2, 1999 or earlier            | http://web.archive.org/web/19990202012404/http://www.gnu.org/copyleft/gpl.txt |
|        | (July 15, 1997 or earlier)             | http://ftp.gnu.org/gnu/grep/grep-2.2.tar.gz (COPYING file dated July 15, 1997, archive dated April 27, 1998) |
| [x] 4  | between October 18, 2000 and December 1, 2000 | http://web.archive.org/web/20001201224600/http://www.fsf.org:80/copyleft/gpl.txt |
| [ ] 5a | between May 1, 2005 and May 11, 2005   | http://web.archive.org/web/20050511030123/http://www.fsf.org:80/licensing/licenses/gpl.txt |
| [ ] 5b | between May 1, 2005 and May 8, 2005    | http://web.archive.org/web/20050508084041/http://www.gnu.org/licenses/gpl.txt |
| [ ] 6a | between May 16, 2006 and May 28, 2006  | http://web.archive.org/web/20060528005322/http://www.fsf.org/licensing/licenses/gpl.txt |
| [ ] 6b | April 7 or 8, 2006                     | http://web.archive.org/web/20060408075851/http://www.gnu.org/licenses/gpl.txt |
| [ ] 7  | between June 15, 2006 and July 1, 2006 | http://web.archive.org/web/20060701033154/http://www.gnu.org/licenses/gpl.txt |

| #      | description | comment |
|--------|-------------|---------|
| [x] 1a | FSF's address at 675 Mass Ave, Cambridge, MA 02139, USA | first version |
| [x] 1b | like 1a but with a spelling mistake | found in an official gcc archive and might only have been used there |
| [x] 2  | 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA | |
| [ ] 3  | "Appendix: " removed from the appendix, address modified (replacing a hyphen with a comma) | |
| [x] 4  | appendix made Y2K-proof | |
| [ ] 5a | 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA | only on fsf.org |
| [ ] 5b | 51 Franklin St, Fifth Floor, Boston, MA  02110-1301, USA | only on gnu.org |
| [ ] 6a | "Library" to "Lesser" in appendix only | only on fsf.org |
| [ ] 6b | "Library" to "Lesser" in appendix and preamble | only on gnu.org |
| [ ] 7  | "Inc." to "Inc.," in preamble, "USA" to "USA." in appendix | only on gnu.org |

**Comment by pombredanne** [comment]
Add added in https://github.com/pombredanne/gpl-history/pull/18
