### ISSUE TITLE
add Linux kernel COPYING versions from historical tree

### ISSUE THREAD

**Issue by armijnhemel** [pombredanne/gpl-history#2]
The following two versions seem to be missing:

* https://git.kernel.org/pub/scm/linux/kernel/git/tglx/history.git/commit/COPYING?id=7a2deb32924142696b8174cdf9b38cd72a11fc96 (different syscall notice)
* https://git.kernel.org/pub/scm/linux/kernel/git/tglx/history.git/commit/COPYING?id=6211a2d822e38a0202f3a395a96272400409d7af (not Y2K proof)

**Comment by pombredanne** [comment]
let me try a git filter branch too there so we can have the whole commit history
