### ISSUE TITLE
add Linux kernel version from kernel 2.2

### ISSUE THREAD

**Issue by armijnhemel** [pombredanne/gpl-history#6]
The version from Linux kernel 2.2.0 is identical to the one from 1.0, except:

* different address
* corrected spelling ("Linux" instead of "linux") in syscall notice

**Comment by pombredanne** [comment]
I went in the available Linux git histories to add all the historical variants I could  find, 
Note that the weirdest one ends up being this (recent) commit by Thomas:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/LICENSES/preferred/GPL-2.0?id=255247c2770ada6edace04173b35307869b47d99
which mentions this repository ;) .... so we are going full circle!  

I have been using your pointers and this https://stackoverflow.com/questions/3264283/linux-kernel-historical-git-repository-with-full-history from @dspinellis

> Here is a review of available 2018 options with a focus on tag availability and date correctness.
> https://archive.org/download/git-history-of-linux/full-history-linux.git.tar
> 
> Developed by Dave Jones, and made available on archive.org.
> 
>     Covers early versions to 2010.
>     244,464 commits
>     Just 184 tags, covering versions in 2.6. The tags that should have been created for all versions seem to be missing.
>     Early commits have realistic dates, but incorrect times (11:00:00 199X -0600).
>     Some dates seem to be incorrect. For example, both 2.1.110 and 2.1.111 are dated Wed May 20 11:00:00 1998 -0600, although the latest file in the 2.1.111 snapshot is dated 1998-07-25 09:17.
>     The creation process is documented on GitHub and seems very thorough.
> 
> https://git.kernel.org/pub/scm/linux/kernel/git/tglx/history.git/
> 
> Created by Thomas Gleixner.
> 
>     Covers 2.4.0 to 2.6.12-rc2.
>     Contains 170 tags covering 2.5.X and 2.6.X.
>     63,428 commits
>     Dates are correct.
>     Contains patches converted into commits.
> 
> https://github.com/mpe/linux-fullhistory
> 
> Created by Michael Ellerman, derived from work by Yoann Padioleau, based on historical trees reconstructed by Dave Jones and Thomas Gleixner, and Linus' mainline tree.
> 
>     Covers full history
>     Provides only 558 tags, mostly starting at 2.0.0.
>     790,471 commits
>     Same issues with dates as in Dave Jones's repo.
>     Uses replace objects instead of grafts.
> 
> https://git.kernel.org/pub/scm/linux/kernel/git/history/history.git/
> 
> Owned by the Linux history team.
> 
>     Covers early versions to 2.6.33-rc5.
>     1710 tags, starting with 0.10, covering most early versions.
>     244,774 commits
>     Most historic versions are incorrectly dated Fri Nov 23 15:09:04 2007 -0500.
> 
> https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/
> 
> Modern Linux development.
> 
>     Covers 2.6.12-rc2 (2005) until today
>     569 tags
>     777,419 commits (August 2018)
>     Proper commits
> 
>

**Comment by pombredanne** [comment]
The versions have been added! The branch-filtered history will follow next to satisfy our discerning license nerdism delight :)

**Comment by armijnhemel** [comment]
I just looked at the tarballs :-)
